-- 1. ELIMINAR TABLAS EXISTENTES (Si existen y no tienen datos importantes)
DROP TABLE IF EXISTS product_images;
DROP TABLE IF EXISTS products;

---
-- 2. CREAR TABLA PRINCIPAL: products
---

CREATE TABLE public.products (
    -- Columnas básicas y obligatorias
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    
    -- Columna de stock (quantity)
    quantity INTEGER NOT NULL DEFAULT 0,
    
    -- Columna opcional
    description TEXT,
    
    -- Columna de auditoría/tiempo
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    -- Restricciones de integridad de datos
    CONSTRAINT check_price_non_negative CHECK (price >= 0),
    CONSTRAINT check_quantity_non_negative CHECK (quantity >= 0)
);

-- 3. HABILITAR RLS (Row Level Security) - Es buena práctica en Supabase
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;

---
-- 4. CREAR TABLA DE IMÁGENES
---

CREATE TABLE public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Enlace al producto (Foreign Key)
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    
    -- URL de la imagen en Supabase Storage
    image_url TEXT NOT NULL,
    
    -- Columna de auditoría/tiempo
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- 5. CREAR ÍNDICE para búsquedas rápidas de imágenes por producto
CREATE INDEX idx_product_images_product_id ON public.product_images(product_id);

-- 6. HABILITAR RLS para product_images
-- ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;

-- Permitir inserciones desde el role 'service_role'
CREATE POLICY "Allow insert from service role"
ON product_images
FOR INSERT
WITH CHECK (auth.role() = 'service_role');
